baseURL: https://gabby-the-tabby.netlify.app/
languageCode: en-us
title: Gabby The Tabby
env: development

summaryLength: 30
paginate: 9

permalinks:
  articles: "/:title"
  categories: "/category/:slug"

taxonomies:
  category: categories
  tag: tags

params:
  description: 'Cat health and behavior advice, cat product reviews.'
  author: Samantha Sheppard
  donate: 

menu:
  main:
  - identifier: home
    name: Home
    url: /
    weight: 1
    pre: house-chimney-heart

  - identifier: information
    name: Information
    url: /category/information
    weight: 2
    pre: newspaper

  - identifier: reviews
    name: Reviews
    url: /category/reviews
    weight: 3
    pre: magnifying-glass-dollar

  - identifier: contact
    name: Contact
    url: /contact
    weight: 4
    pre: paper-plane

  social:
  - identifier: youtube
    name: YouTube
    url: 'https://www.youtube.com/channel/UCiIqBLPEh8JDbr05X8mKa_g'
    weight: 1
    pre: youtube

  - identifier: twitter
    name: Twitter
    url: 'https://twitter.com/therealgabbycat'
    weight: 4
    pre: twitter

  - identifier: instagram
    name: Instagram
    url: 'https://www.instagram.com/gabby.the.tabby/'
    weight: 2
    pre: instagram

  - identifier: facebook
    name: Facebook
    url: 'https://www.facebook.com/gabbythetabbyofficial'
    weight: 3
    pre: facebook