baseURL: 'https://www.gabbythetabby.com/'
languageCode: en-us
title: Gabby The Tabby

summaryLength: 30
paginate: 6

permalinks:
  articles: "/:title"
  categories: "/category/:slug"

taxonomies:
  category: categories
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  description: 'Cat health and behavior advice, cat product reviews.'
  author: Samantha Sheppard
  donate: 

menu:
  main:
  - identifier: home
    name: Home
    url: /
    weight: 1
    pre: home

  - identifier: information
    name: Information
    url: /category/information
    weight: 2
    pre: Information

  - identifier: reviews
    name: Reviews
    url: /category/reviews
    weight: 3
    pre: Reviews

  - identifier: contact
    name: Contact
    url: /contact
    weight: 4
    pre: Contact

  social:
  - identifier: youtube
    name: YouTube
    url: 'https://www.youtube.com/channel/UCiIqBLPEh8JDbr05X8mKa_g'
    weight: 1
    pre: <i class="fa-brands fa-youtube fa-fw"></i>

  - identifier: twitter
    name: Twitter
    url: 'https://twitter.com/therealgabbycat'
    weight: 4
    pre: <i class="fa-brands fa-twitter fa-fw"></i>

  - identifier: instagram
    name: Instagram
    url: 'https://www.instagram.com/gabby.the.tabby/'
    weight: 2
    pre: <i class="fa-brands fa-instagram fa-fw"></i>

  - identifier: facebook
    name: Facebook
    url: 'https://www.facebook.com/gabbythetabbyofficial'
    weight: 3
    pre: <i class="fa-brands fa-facebook fa-fw"></i>